In [ ]:
# Lab03 Numpy Basics

In [1]:
# NumPy Basics
import numpy as np

s = np.arange(12)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# 1) Show all element of s
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 2) Show the third element of s
print(s[2])

# 2) Show the last element of s
print(s[-1])

2
11


In [5]:
# 3) Show the third to last element of s
print(s[2:])

# Show the third to seventh element of s
print(s[2:7])

[ 2  3  4  5  6  7  8  9 10 11]
[2 3 4 5 6]


In [6]:

# 4) Show the total of s
print(sum(s))

# Show the smallest value of s
print(s.min())

# Show the average value of s
print(s.mean())

# Show the largest value of s
print(s.max())

66
0
5.5
11


In [8]:
# 5) if array change values, will s change values too? why?
# show s values
arry = s
arry[1]= -1
print(s)
print(arry)

[ 0 -1  2  3  4  5  6  7  8  9 10 11]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [9]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
print(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
matrix = np.array(data)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# 6)Show the element of first row of second col of matrix
print(matrix[0,1])

# 6)Show the element of second row of first col of matrix
print(matrix[1,0])

2
4


In [21]:
# 7 )Show all elements of first row in matrix
print(matrix[0])
print('----------')
#  Show all elements of second row in matrix
print(matrix[1])
print('----------')
# Show all elements of last row in matrix
print(matrix[2])
print('-----------')

[1 2 3]
----------
[4 5 6]
----------
[7 8 9]
-----------


In [26]:
# 8) Show all elements of first col in matrix
print(matrix[:,0])
print('-----------')
# Show all elements of third col in matrix
print(matrix[:,2])
print('-----------')
# Show all elements of last col in matrix
print(matrix[:,-1])
print('-----------')

[1 4 7]
-----------
[3 6 9]
-----------
[3 6 9]
-----------


In [27]:
print( matrix)
# Show second rows, and second col to last col's elements in matrix

print(matrix[1, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]


In [29]:
print(matrix)
# 9) Show the total of matrix
print(sum(matrix))
print('-----------')
# Show the smallest value of matrix
print(matrix.min())
print('-----------')
# Show the average value of matrix
print(matrix.mean())
print('-----------')
# Show the largest value of matrix
print(matrix.max())
print('-----------')
# The sum of second col
print(sum(matrix[:,1]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
-----------
1
-----------
5.0
-----------
9
-----------
15
